# Generated by Django 4.1.1 on 2022-09-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Гильдия",
                "verbose_name_plural": "Гильдии",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="rang",
            field=models.CharField(
                choices=[
                    ("GAYNIN", "Генин"),
                    ("CHUNIN", "Чунин"),
                    ("JONIN", "Джоунин"),
                    ("ELITE_JONIN", "Элитный Джоунин"),
                    ("ANBU_JONIN", "Анбу"),
                    ("AKATSUKI_MEMBER", "Акацуки"),
                    ("LEGENDARY_SANIN", "Легендарный Санин"),
                    ("KAGE", "Каге"),
                ],
                default="GAYNIN",
                max_length=50,
                verbose_name="Ранг",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="profiles.guild",
                verbose_name="Гильдия",
            ),
        ),
    ]
