# Generated by Django 4.1.1 on 2022-09-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_guild_profile_rang_profile_guild"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="descrition",
            field=models.TextField(
                default="Fucking slaves", verbose_name="Описание гильдии"
            ),
            preserve_default=False,
        ),
    ]
