# Generated by Django 4.1.1 on 2022-09-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_guild_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guild",
            old_name="descrition",
            new_name="description",
        ),
    ]
